# number of bits for weight and activation
BITS_WEIGHTS = 32
BITS_ACTIVATION = 32

# unit Energy (/one bit)
UNIT_ENERGY_MULTI = 0.0004
UNIT_ENERGY_ADDER = 0.00002
UNIT_ENERGY_MAXP = 0.0003
UNIT_ENERGY_BATCHNORM = 0.0003
UNIT_ENERGY_RELU = 0.0003
UNIT_ENERGY_WRITE = 0.00002
UNIT_ENERGY_DATA_toPE_fmBUFIMG = 0.00002
UNIT_ENERGY_DATA_toPE_fmBUFACT = 0.00002
UNIT_ENERGY_DATA_toPE_fmAdderReLU = 0.00002
UNIT_ENERGY_DATA_toAdderReLU_fmPE = 0.00002
UNIT_ENERGY_DATA_toAdderReLU_fmMAXP = 0.00002
UNIT_ENERGY_DATA_toMAXP_fmPE = 0.00002
UNIT_ENERGY_DATA_toMAXP_fmBUFACT = 0.00002
UNIT_ENERGY_DATA_toMAXP_fmPE = 0.00002
UNIT_ENERGY_DATA_toMAXP_fmAdderReLU = 0.00002
UNIT_ENERGY_DATA_toBUFACT_fmPE = 0.00002
UNIT_ENERGY_DATA_toBUFACT_fmMAXP = 0.00002
UNIT_ENERGY_DATA_toBUFACT_fmBATCHNORM = 0.00002
UNIT_ENERGY_DATA_toBUFACT_fmAdderReLU = 0.00002


# unit Cycle
UNIT_CYCLE_MULTI = 8   # [cycles/run]
UNIT_CYCLE_ADDER = 4   # [cycles/run]
UNIT_CYCLE_MAXP = 4    # [cycles/run]
UNIT_CYCLE_BATCHNORM = 4   # [cycles/run]
UNIT_CYCLE_RELU = 4    # [cycles/run]
UNIT_CYCLE_WRITE = 1   # [cycles/bit]
UNIT_CYCLE_DATA_toBUFACT_fmPE = 1  # [cycles/bit]
UNIT_CYCLE_DATA_toBUFACT_fmMAXP = 1 # [cycles/bit]
UNIT_CYCLE_DATA_toBUFACT_fmBATCHNORM = 1 # [cycles/bit]
UNIT_CYCLE_DATA_toBUFACT_fmAdderReLU = 1 # [cycles/bit]



# unit
UNIT_LATENCY = 0.000005 # ms/cycle
NUM_BITS = 8 #bits/one number
